### ISSUE TITLE
noisyMax with Gap?

### ISSUE THREAD

**Issue by hengchu** [cmla-psu/shadowdp#1]
In the "Free Gap Information" paper (https://arxiv.org/pdf/1904.12773.pdf), Ding et. al. proposed a novel variant of noisyMax that releases the gap between the noisy max and runner-up with no extra privacy cost. Can shadowDP verify this algorithm?

Thanks!

**Comment by yuxincs** [comment]
Hi @hengchu,

Thanks for your interests in our work!

Unfortunately, ShadowDP is not capable of verifying that variant for now. For example, let's use ``sq`` to track the second largest element seen so far (where we use ``bq`` to track the current largest). Whenever a new ``bq`` is found, ShadowDP is able to "forget" all previous alignments, which is essential for noisy max since we only want to align the max. However, that also erases the alignment for ``sq``, so the gap ``bq - sq`` wouldn't be aligned anymore. We believe ShadowDP needs to be extended to be more expressive in terms of alignments to verify this variant.

However, the good news is that the underlying proof technique (i.e., Randomness Alignment, which is also used in the FreeGap paper) is powerful enough for those variants. Intuitively, we want to align the maximum queries and the gap between the max and runner-up, as described in the FreeGap paper.

Feel free to follow up if you still have questions!

**Comment by hengchu** [comment]
Thanks for the quick response!
